/*
  # Create Nutritional Standards Table

  1. New Tables
    - `nutritional_standards`
      - `id` (bigint, primary key) - Auto-generated ID
      - `nutrient_key` (text, unique) - Key identifier (e.g., 'vit_c_mg', 'omega_3_total_g')
      - `label` (text) - Display name (e.g., 'Vitamina C')
      - `unit` (text) - Unit of measurement (e.g., 'mg', 'g', 'mcg', 'UI')
      - `min_survival_value` (numeric) - Level 1: RDA (Recommended Daily Allowance)
      - `min_optimal_value` (numeric) - Level 2: ODI (Optimal Daily Intake for biohacking)
      - `max_optimal_value` (numeric) - Maximum safe level (toxicity threshold)
      - `category` (text) - Group: 'macro', 'vitamin', 'mineral', 'lipid', 'amino'
      - `color_code` (text) - Hex color for UI representation
      - `description` (text) - Explanation of the nutrient's role
      - `created_at` (timestamptz) - Timestamp

  2. Master Data
    - Inserts comprehensive nutritional standards based on RDA and optimal biohacking levels
    - Covers macros, vitamins, minerals, lipids, and amino acids

  3. Security
    - Enable RLS on `nutritional_standards` table
    - Public read access (standards are universal)
    - No write access from frontend (data is managed via migrations)
*/

CREATE TABLE IF NOT EXISTS nutritional_standards (
  id bigint generated by default as identity primary key,
  nutrient_key text not null unique,
  label text not null,
  unit text not null,
  min_survival_value numeric not null,
  min_optimal_value numeric,
  max_optimal_value numeric,
  category text not null,
  color_code text default '#3b82f6',
  description text,
  created_at timestamptz default now()
);

ALTER TABLE nutritional_standards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Nutritional standards are publicly readable"
  ON nutritional_standards FOR SELECT
  TO authenticated
  USING (true);

-- MACRONUTRIENTES
INSERT INTO nutritional_standards (nutrient_key, label, unit, category, min_survival_value, min_optimal_value, max_optimal_value, color_code, description) VALUES
('protein_g', 'Proteína', 'g', 'macro', 50, 120, 200, '#3b82f6', 'Esencial para reparación muscular y función inmune'),
('carbs_g', 'Carbohidratos', 'g', 'macro', 130, 150, 300, '#10b981', 'Fuente principal de energía'),
('fat_g', 'Grasas Totales', 'g', 'macro', 44, 70, 120, '#f59e0b', 'Necesarias para hormonas y absorción de vitaminas'),
('fiber_g', 'Fibra', 'g', 'macro', 25, 35, 50, '#8b5cf6', 'Salud digestiva y control glucémico'),
('sugar_g', 'Azúcares', 'g', 'macro', 0, 0, 25, '#ef4444', 'Limitar para prevenir inflamación');

-- VITAMINAS
INSERT INTO nutritional_standards (nutrient_key, label, unit, category, min_survival_value, min_optimal_value, max_optimal_value, color_code, description) VALUES
('vitamin_a_mcg', 'Vitamina A', 'mcg', 'vitamin', 900, 1500, 3000, '#f59e0b', 'Visión, inmunidad, piel'),
('vitamin_c_mg', 'Vitamina C', 'mg', 'vitamin', 90, 500, 2000, '#10b981', 'Antioxidante, colágeno, inmunidad'),
('vitamin_d_mcg', 'Vitamina D3', 'mcg', 'vitamin', 15, 50, 100, '#fbbf24', 'Huesos, inmunidad, estado de ánimo'),
('vitamin_e_mg', 'Vitamina E', 'mg', 'vitamin', 15, 30, 1000, '#34d399', 'Antioxidante, protección celular'),
('vitamin_k_mcg', 'Vitamina K', 'mcg', 'vitamin', 120, 200, 1000, '#059669', 'Coagulación, salud ósea'),
('vitamin_b6_mg', 'Vitamina B6', 'mg', 'vitamin', 1.7, 5, 100, '#3b82f6', 'Metabolismo, función cerebral'),
('vitamin_b12_mcg', 'Vitamina B12', 'mcg', 'vitamin', 2.4, 10, 1000, '#6366f1', 'Energía, nervios, ADN'),
('folate_mcg', 'Folato (B9)', 'mcg', 'vitamin', 400, 600, 1000, '#8b5cf6', 'División celular, prevención de defectos');

-- MINERALES
INSERT INTO nutritional_standards (nutrient_key, label, unit, category, min_survival_value, min_optimal_value, max_optimal_value, color_code, description) VALUES
('calcium_mg', 'Calcio', 'mg', 'mineral', 1000, 1200, 2500, '#f3f4f6', 'Huesos, dientes, contracción muscular'),
('iron_mg', 'Hierro', 'mg', 'mineral', 8, 18, 45, '#dc2626', 'Transporte de oxígeno, energía'),
('magnesium_mg', 'Magnesio', 'mg', 'mineral', 400, 500, 700, '#10b981', 'Más de 300 reacciones enzimáticas, sueño, estrés'),
('potassium_mg', 'Potasio', 'mg', 'mineral', 3400, 4700, 6000, '#f59e0b', 'Presión arterial, función muscular'),
('sodium_mg', 'Sodio', 'mg', 'mineral', 500, 1500, 2300, '#ef4444', 'Balance de fluidos (limitar)'),
('zinc_mg', 'Zinc', 'mg', 'mineral', 11, 15, 40, '#6b7280', 'Inmunidad, cicatrización, testosterona');

-- NOTA: Los lípidos y aminoácidos específicos se pueden agregar más tarde
-- cuando la IA comience a reportarlos en el nutritional_matrix
