/*
  # Chat Messages Table for Health Assistant
  
  ## Overview
  Creates a table to store chat messages between users and the AI health assistant,
  enabling persistent conversation history and integration with n8n.
  
  ## New Tables
  
  ### `chat_messages`
  Stores all chat messages exchanged between users and the health assistant
  - `id` (bigint, primary key) - Unique message identifier
  - `user_id` (uuid, foreign key) - References auth.users
  - `content` (text) - The message content
  - `sender` (text) - Either 'user' or 'assistant'
  - `metadata` (jsonb) - Optional structured data (macros, recommendations, etc.)
  - `created_at` (timestamptz) - When the message was created
  
  ## Security
  
  ### Row Level Security (RLS)
  - Enable RLS on chat_messages table
  - Users can view their own messages
  - Users can insert their own messages (when sending)
  - Service role can insert assistant messages (for n8n integration)
  
  ## Important Notes
  
  ### n8n Integration
  For n8n to write assistant responses back to the database, it needs:
  1. The Supabase URL (SUPABASE_URL from .env)
  2. The service_role_key (SUPABASE_SERVICE_ROLE_KEY)
  3. Use the Supabase client in n8n with service_role_key to bypass RLS
  
  ### Security Considerations
  - Only authenticated users can read their own messages
  - Users can only insert messages with sender='user'
  - Service role (n8n) can insert messages with sender='assistant'
  - No deletion policy to maintain conversation history
*/

-- Create chat_messages table
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  content TEXT NOT NULL,
  sender TEXT NOT NULL CHECK (sender IN ('user', 'assistant')),
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own messages
CREATE POLICY "Users can view own chat messages"
  ON public.chat_messages FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own messages (when sending as 'user')
CREATE POLICY "Users can insert own messages"
  ON public.chat_messages FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id AND sender = 'user');

-- Policy: Service role can insert assistant messages
-- Note: This policy uses service_role which bypasses RLS anyway,
-- but we add it for clarity and potential future use cases
CREATE POLICY "Service role can insert assistant messages"
  ON public.chat_messages FOR INSERT
  TO service_role
  WITH CHECK (sender = 'assistant');

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id 
  ON public.chat_messages(user_id);

CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at 
  ON public.chat_messages(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_chat_messages_user_created 
  ON public.chat_messages(user_id, created_at DESC);
