/*
  # Comprehensive Nutrition Tracking System
  
  ## Overview
  This migration creates a complete nutrition tracking system with support for:
  - Detailed macro and micronutrient tracking
  - Personalized daily goals and targets
  - User profiles with custom nutrition plans
  - Historical food logging with full nutritional breakdown
  
  ## New Tables
  
  ### 1. `profiles`
  User profile table with personal nutrition targets
  - `id` (uuid, primary key) - References auth.users
  - `full_name` (text) - User's full name
  - `email` (text) - User's email
  - `age` (int) - Age for personalized recommendations
  - `gender` (text) - Gender (male/female/other)
  - `height_cm` (int) - Height in centimeters
  - `weight_kg` (numeric) - Current weight in kilograms
  - `activity_level` (text) - Activity level (sedentary/light/moderate/active/very_active)
  - `goal` (text) - User goal (lose_weight/maintain/gain_muscle)
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)
  
  ### 2. `daily_goals`
  Personalized daily nutrition targets for each user
  - `id` (bigint, primary key)
  - `user_id` (uuid) - References auth.users
  - `calories` (int) - Target calories
  - `protein_g` (numeric) - Target protein in grams
  - `carbs_g` (numeric) - Target carbohydrates in grams
  - `fat_g` (numeric) - Target fat in grams
  - `fiber_g` (numeric) - Target fiber in grams
  - `water_ml` (int) - Target water intake in ml
  - Micronutrients (vitamins & minerals)
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)
  
  ### 3. `food_logs`
  Daily food intake logs with complete nutritional information
  - `id` (bigint, primary key)
  - `user_id` (uuid) - References auth.users
  - `food_name` (text) - Name of food/meal
  - `serving_size` (text) - Serving size description
  - `meal_type` (text) - breakfast/lunch/dinner/snack
  - All macro and micronutrients
  - `logged_at` (timestamptz) - When the food was consumed
  - `created_at` (timestamptz)
  
  ### 4. `water_logs`
  Water intake tracking
  - `id` (bigint, primary key)
  - `user_id` (uuid) - References auth.users
  - `amount_ml` (int) - Amount of water in ml
  - `logged_at` (timestamptz)
  
  ## Security
  - Enable RLS on all tables
  - Users can only access their own data
  - Authenticated users can create, read, and update their own records
  - No user can delete historical data (for data integrity)
*/

-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  age INT,
  gender TEXT DEFAULT 'other',
  height_cm INT,
  weight_kg NUMERIC(5,2),
  activity_level TEXT DEFAULT 'moderate',
  goal TEXT DEFAULT 'maintain',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create daily_goals table
CREATE TABLE IF NOT EXISTS public.daily_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  
  -- Macronutrients
  calories INT DEFAULT 2000,
  protein_g NUMERIC(6,2) DEFAULT 150,
  carbs_g NUMERIC(6,2) DEFAULT 250,
  fat_g NUMERIC(6,2) DEFAULT 65,
  fiber_g NUMERIC(5,2) DEFAULT 30,
  sugar_g NUMERIC(6,2) DEFAULT 50,
  
  -- Hydration
  water_ml INT DEFAULT 2000,
  
  -- Vitamins
  vitamin_a_mcg NUMERIC(6,2) DEFAULT 900,
  vitamin_c_mg NUMERIC(6,2) DEFAULT 90,
  vitamin_d_mcg NUMERIC(6,2) DEFAULT 15,
  vitamin_e_mg NUMERIC(6,2) DEFAULT 15,
  vitamin_k_mcg NUMERIC(6,2) DEFAULT 120,
  vitamin_b6_mg NUMERIC(6,2) DEFAULT 1.7,
  vitamin_b12_mcg NUMERIC(6,2) DEFAULT 2.4,
  folate_mcg NUMERIC(6,2) DEFAULT 400,
  
  -- Minerals
  calcium_mg NUMERIC(6,2) DEFAULT 1000,
  iron_mg NUMERIC(6,2) DEFAULT 8,
  magnesium_mg NUMERIC(6,2) DEFAULT 400,
  potassium_mg NUMERIC(6,2) DEFAULT 3500,
  sodium_mg NUMERIC(6,2) DEFAULT 2300,
  zinc_mg NUMERIC(6,2) DEFAULT 11,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(user_id)
);

-- Create food_logs table
CREATE TABLE IF NOT EXISTS public.food_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  
  food_name TEXT NOT NULL,
  serving_size TEXT DEFAULT '100g',
  meal_type TEXT DEFAULT 'snack',
  
  -- Macronutrients
  calories INT DEFAULT 0,
  protein_g NUMERIC(6,2) DEFAULT 0,
  carbs_g NUMERIC(6,2) DEFAULT 0,
  fat_g NUMERIC(6,2) DEFAULT 0,
  fiber_g NUMERIC(5,2) DEFAULT 0,
  sugar_g NUMERIC(6,2) DEFAULT 0,
  
  -- Vitamins
  vitamin_a_mcg NUMERIC(6,2) DEFAULT 0,
  vitamin_c_mg NUMERIC(6,2) DEFAULT 0,
  vitamin_d_mcg NUMERIC(6,2) DEFAULT 0,
  vitamin_e_mg NUMERIC(6,2) DEFAULT 0,
  vitamin_k_mcg NUMERIC(6,2) DEFAULT 0,
  vitamin_b6_mg NUMERIC(6,2) DEFAULT 0,
  vitamin_b12_mcg NUMERIC(6,2) DEFAULT 0,
  folate_mcg NUMERIC(6,2) DEFAULT 0,
  
  -- Minerals
  calcium_mg NUMERIC(6,2) DEFAULT 0,
  iron_mg NUMERIC(6,2) DEFAULT 0,
  magnesium_mg NUMERIC(6,2) DEFAULT 0,
  potassium_mg NUMERIC(6,2) DEFAULT 0,
  sodium_mg NUMERIC(6,2) DEFAULT 0,
  zinc_mg NUMERIC(6,2) DEFAULT 0,
  
  logged_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create water_logs table
CREATE TABLE IF NOT EXISTS public.water_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  amount_ml INT NOT NULL,
  logged_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.water_logs ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

-- Daily goals policies
CREATE POLICY "Users can view own goals"
  ON public.daily_goals FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update own goals"
  ON public.daily_goals FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can insert own goals"
  ON public.daily_goals FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Food logs policies
CREATE POLICY "Users can view own food logs"
  ON public.food_logs FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own food logs"
  ON public.food_logs FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own food logs"
  ON public.food_logs FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own food logs"
  ON public.food_logs FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Water logs policies
CREATE POLICY "Users can view own water logs"
  ON public.water_logs FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own water logs"
  ON public.water_logs FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own water logs"
  ON public.water_logs FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_food_logs_user_id ON public.food_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_food_logs_logged_at ON public.food_logs(logged_at);
CREATE INDEX IF NOT EXISTS idx_water_logs_user_id ON public.water_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_water_logs_logged_at ON public.water_logs(logged_at);